import type { ScenePackage } from './types';
import type { CardDefinition, PageSchema, StrategyPageSchema } from '../platform/types';
import { linkageLabels } from '../data/app-alignment';
import { linkageSectionsFor } from './greenhouse-pack';

/**
 * 专业灌溉场景包：大田/果园轮灌、墒情驱动、水源与泵房。
 * 卡片类型复用平台 CardType；分组为气象 / 土壤 / 水源与水质 / 泵房能耗。
 */
const irrigationCards: CardDefinition[] = [
  {
    type: 'temperature',
    title: '气温',
    unit: '℃',
    icon: 'thermometer',
    colorClass: 'text-red-500',
    bgClass: 'bg-red-50',
    alarmBgClass: 'bg-red-500',
    category: 'metric',
    defaultMetricKeys: ['temperature'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '参考蒸散与灌溉窗口。',
  },
  {
    type: 'humidity',
    title: '空气湿度',
    unit: '%',
    icon: 'droplets',
    colorClass: 'text-blue-500',
    bgClass: 'bg-blue-50',
    alarmBgClass: 'bg-blue-500',
    category: 'metric',
    defaultMetricKeys: ['humidity'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '与叶面湿润、喷灌蒸发相关。',
  },
  {
    type: 'pressure',
    title: '气压',
    unit: 'hPa',
    icon: 'gauge',
    colorClass: 'text-gray-500',
    bgClass: 'bg-gray-50',
    alarmBgClass: 'bg-gray-500',
    category: 'metric',
    defaultMetricKeys: ['pressure'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '气象站参考。',
  },
  {
    type: 'light',
    title: '日照',
    unit: 'lux',
    icon: 'sun',
    colorClass: 'text-yellow-500',
    bgClass: 'bg-yellow-50',
    alarmBgClass: 'bg-yellow-500',
    category: 'metric',
    defaultMetricKeys: ['light'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '粗略反映日辐射，可与计划灌水量联动（Demo 纯展示）。',
  },
  {
    type: 'soilTemp',
    title: '地温',
    unit: '℃',
    icon: 'thermometer',
    colorClass: 'text-orange-600',
    bgClass: 'bg-orange-50',
    alarmBgClass: 'bg-orange-500',
    category: 'metric',
    defaultMetricKeys: ['soilTemp'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '根层温度，辅助判断吸水与蒸发。',
  },
  {
    type: 'soilHumidity',
    title: '土壤体积含水',
    unit: '%',
    icon: 'droplets',
    colorClass: 'text-lime-600',
    bgClass: 'bg-lime-50',
    alarmBgClass: 'bg-lime-500',
    category: 'metric',
    defaultMetricKeys: ['soilHumidity'],
    hasLinkage: true,
    hasLinkageStrategy: true,
    description: '墒情主控量；可进入灌溉联动策略（与温室基质策略同结构）。',
  },
  {
    type: 'waterTemp',
    title: '源水水温',
    unit: '℃',
    icon: 'thermometer',
    colorClass: 'text-cyan-500',
    bgClass: 'bg-cyan-50',
    alarmBgClass: 'bg-cyan-500',
    category: 'metric',
    defaultMetricKeys: ['waterTemp'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '蓄水池/河道取水点。',
  },
  {
    type: 'waterLevel',
    title: '蓄水池液位',
    unit: 'm',
    icon: 'waves',
    colorClass: 'text-cyan-600',
    bgClass: 'bg-cyan-50',
    alarmBgClass: 'bg-cyan-500',
    category: 'metric',
    defaultMetricKeys: ['waterLevel'],
    hasLinkage: true,
    hasLinkageStrategy: true,
    description: '液位联保停泵/补水阀（与温室营养液液位同一策略壳）。',
  },
  {
    type: 'ec',
    title: '源水电导',
    unit: 'mS/cm',
    icon: 'zap',
    colorClass: 'text-emerald-500',
    bgClass: 'bg-emerald-50',
    alarmBgClass: 'bg-emerald-500',
    category: 'metric',
    defaultMetricKeys: ['ec'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '若接肥液灌，可作水质哨兵（Demo 展示）。',
  },
  {
    type: 'ph',
    title: '源水 pH',
    unit: '',
    icon: 'flask',
    colorClass: 'text-indigo-500',
    bgClass: 'bg-indigo-50',
    alarmBgClass: 'bg-indigo-500',
    category: 'metric',
    defaultMetricKeys: ['ph'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '酸碱度巡检。',
  },
  {
    type: 'energy',
    title: '泵房电能',
    unit: '',
    icon: 'zap',
    colorClass: 'text-purple-600',
    bgClass: 'bg-purple-50',
    alarmBgClass: 'bg-purple-500',
    category: 'energy',
    defaultMetricKeys: ['power', 'energy'],
    hasLinkage: false,
    hasLinkageStrategy: false,
    description: '泵站主回路功率与电量。',
  },
];

const irrigationStrategyPages: StrategyPageSchema[] = (['soilHumidity', 'waterLevel'] as const).map(key => ({
  id: `policy.irrigation.${key}`,
  sceneKey: 'irrigation',
  policyKey: key,
  title: linkageLabels[key].label,
  sections: linkageSectionsFor(key),
}));

const defaultIrrigationPage: PageSchema = {
  id: 'page.irrigation.realtime.default',
  sceneKey: 'irrigation',
  name: '灌溉项目 · 实时',
  pageKey: 'realtime',
  groups: [
    { key: 'meteo', label: '气象参考', order: 0 },
    { key: 'soil', label: '土壤墒情', order: 1 },
    { key: 'hydraulics', label: '水源与水质', order: 2 },
    { key: 'energy', label: '泵房能耗', order: 3 },
  ],
  cards: [
    ...(['temperature', 'humidity', 'pressure', 'light'] as const).map((type, order) => ({
      id: `irr-m-${type}`,
      type,
      layoutGroup: 'meteo',
      enabled: true,
      order,
    })),
    ...(['soilTemp', 'soilHumidity'] as const).map((type, order) => ({
      id: `irr-s-${type}`,
      type,
      layoutGroup: 'soil',
      enabled: true,
      order,
    })),
    ...(['waterTemp', 'waterLevel', 'ec', 'ph'] as const).map((type, order) => ({
      id: `irr-h-${type}`,
      type,
      layoutGroup: 'hydraulics',
      enabled: true,
      order,
    })),
    { id: 'irr-e', type: 'energy', layoutGroup: 'energy', enabled: true, order: 0 },
  ],
};

export const irrigationScenePackage: ScenePackage = {
  key: 'irrigation',
  name: '专业灌溉',
  tagline: '气象参考、墒情驱灌、水源水质与泵房能耗一体监控',
  status: 'active',
  capabilities: [
    { key: 'zones', label: '灌溉分区 / 轮灌组' },
    { key: 'schedule', label: '计划与墒情触发' },
    { key: 'valve-pump', label: '阀泵联锁' },
    { key: 'water-quality', label: '源水水质哨兵' },
  ],
  cardPalette: irrigationCards,
  defaultPage: defaultIrrigationPage,
  strategyPages: irrigationStrategyPages,
};
